name: examples.hello_world

environment:
  sdk: ">=2.0.0-dev.28.0 <2.0.0"

dependencies:
  angular: ^5.0.0-alpha

dev_dependencies:
  build_runner: ^0.8.0
  build_test: ^0.10.1+1
  build_web_compilers: ^0.3.4+1
